<?php

return [
    'type' => [
        'fill'           => 'З заливкою',
        'fill_stretch'   => 'З заливкою (на всю ширину)',
        'stroke'         => 'З бордером',
        'stroke_stretch' => 'З бордером (на всю ширину)',
        'simple'         => 'Посилання',
        'text'           => 'Текст',
    ],
    'icon' => [
        'non'                => 'Без іконки',
        'icon-02'            => 'icon-02',
        'icon-03'            => 'icon-03',
        'icon-04'            => 'icon-04',
        'icon-05'            => 'icon-05',
        'icon-06'            => 'icon-06',
        'icon-07'            => 'icon-07',
        'icon-08'            => 'icon-08',
        'icon-09'            => 'icon-09',
        'icon-10'            => 'icon-10',
        'icon-11'            => 'icon-11',
        'icon-12'            => 'icon-12',
        'icon-13'            => 'icon-13',
        'icon-emoji-01'      => 'icon-emoji-01',
        'icon-emoji-02'      => 'icon-emoji-02',
        'icon-emoji-03'      => 'icon-emoji-03',
        'icon-emoji-04'      => 'icon-emoji-04',
        'icon-emoji-05'      => 'icon-emoji-05',
        'icon-arrow-left'    => 'icon-arrow-left',
        'icon-arrow-right'   => 'icon-arrow-right',
        'icon-check'         => 'icon-check',
        'icon-close'         => 'icon-close',
        'icon-plus'          => 'icon-plus',
        'icon-play'          => 'icon-play',
        'icon-send'          => 'icon-send',
        'icon-facebook'      => 'icon-facebook',
        'icon-telegram'      => 'icon-telegram',
        'icon-twitter'       => 'icon-twitter',
        'icon-link'          => 'icon-link',
        'icon-arrow-left-2'  => 'icon-arrow-left-2',
        'icon-arrow-right-2' => 'icon-arrow-right-2'
    ]
];
